apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: roboshop
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  selector:
    component: mongodb
    project: roboshop
    tier: database
  clusterIP: None  # This makes the service headless
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---