apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    component: mongodb-service
spec:
  selector:
    component: mongodb
    project: roboshop
    tier: database
  ports:  
  - protocol: TCP
    port: 27017
    targetPort: 27017

---
