apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    component: mysql-service
spec:
  selector:
    component: mysql
    project: roboshop
    tier: database
  ports:  
  - protocol: TCP
    port: 3306
    targetPort: 3306

---

