apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: roboshop
  labels:
    purpose: service_demo
    project: roboshop
    tier: database
spec:
  selector:
    component: mysql
    project: roboshop
    tier: database
  clusterIP: None  # This makes the service headless
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---